In [10]:
!pip install yt

    100% |████████████████████████████████| 14.8MB 2.2MB/s ta 0:00:011    88% |████████████████████████████▎   | 13.1MB 2.8MB/s eta 0:00:01


In [18]:
!pip install xmltodict

In [81]:
import numpy as np
import zlib
import base64
import xmltodict
import yt

In [82]:
x = open("/Users/swalkow2/Documents/yt/Datasets/Geoscience/solution-00100.0000.vtu", "rb").readlines()

In [3]:
x[:15]

[b'<?xml version="1.0" ?> \n',
 b'<!-- \n',
 b'# vtk DataFile Version 3.0\n',
 b'#This file was generated by the deal.II library on 15:49:41 at 2018/10/5\n',
 b'-->\n',
 b'<VTKFile type="UnstructuredGrid" version="0.1" compressor="vtkZLibDataCompressor" byte_order="LittleEndian">\n',
 b'<UnstructuredGrid>\n',
 b'<FieldData>\n',
 b'<DataArray type="Float32" Name="CYCLE" NumberOfTuples="1" format="ascii">501</DataArray>\n',
 b'<DataArray type="Float32" Name="TIME" NumberOfTuples="1" format="ascii">1e+07</DataArray>\n',
 b'</FieldData>\n',
 b'<Piece NumberOfPoints="33088" NumberOfCells="4136" >\n',
 b'  <Points>\n',
 b'    <DataArray type="Float32" NumberOfComponents="3" format="binary">\n',
 b'AQAAAAAPBgAADwYA9L8AAA==eNqUvX3sZlV591uPVh0rgtqnIeQ3R89p4gs9kTZYE0wIreV3Izkx+oc5UB9lGJCX5041NqFacZwxHmTowzEx0UqNN6c1GjX8YWHagiiFQHGERJ7wEo1wkhEdcwI8ijl/mAyTBzj75bvW/uy913ff1/olxN3Vz3yv7772Wte97nWvvffv/A7+/mxn93dK/3f7v5P/308/tDe3HWuPxeX25r9jYPr//2Z3pJ31N7ujWElT/LMzzZ5/FnGLPlO8rn0ce+ZT/NC+Gfw7n1l/szu

In [4]:
d = x[14]

In [32]:
type(d)

bytes

In [47]:
d

b'AQAAAAAPBgAADwYA9L8AAA==eNqUvX3sZlV591uPVh0rgtqnIeQ3R89p4gs9kTZYE0wIreV3Izkx+oc5UB9lGJCX5041NqFacZwxHmTowzEx0UqNN6c1GjX8YWHagiiFQHGERJ7wEo1wkhEdcwI8ijl/mAyTBzj75bvW/uy913ff1/olxN3Vz3yv7772Wte97nWvvffv/A7+/mxn93dK/3f7v5P/308/tDe3HWuPxeX25r9jYPr//2Z3pJ31N7ujWElT/LMzzZ5/FnGLPlO8rn0ce+ZT/NC+Gfw7n1l/szuOVfA50uz57L8mn/p77EM3Z/6n7bH43N7925t3q/NJTfFPzzR7/mnEDefT+RQ/tG8G/zX5dD5Hmj3/NM6x+7v0mXHfSde6bWcfSDkUv+eSiTfxXftIc2c1ijX0pdUoVtbs+bMumWiKPwtxiz7TuXXtm1EfnvlkDsXvQdyiz6HPr8axCj6pKT77r8kn+6T4l10yudbiu/bafI40e/7MSyaa4s9E3HA+nU/2SfEvQ9xwPp1Paorv2pfqZOq7bftkbBTHdcPk9ub4GJhincz6m91RLDeus2bPP4u4ZZ8ab31NGI29mU/xqGOrY2DKPpP+ZncUq+RzpNnzz26rk9ZnoU6Kz+3dv715tzqftk5Ss+efRtxwPp1P8fhcWP0UTDifzudIs+efxjkW62S61u3/sg+4cZ28id+DcVqsk0NfWo1iuXGdNMWfhbhln+qTfU1Y8bxmPplD8XsQt+wz9/nVKFbJJzXFn7WtTlqfhTrJay3+Zah74Xy6OklN8Wcibjifzif7pPiXIW44n84nNcXn+l8zn9Tfd179q8zf3h6Lz+3Nf7eDCc8nqSn+4Zlmzz+MuOH5pPMpfmjfDP6r5pPG50iz57P/mnzq764P7c1zsfvaY/G5vfnvPjDhfFJT/GMzzZ5/DHHD+XQ+xQ/tm8F/TT6dz5Fmzz+GcwzPJ5lD8c9NvYl/Dkx4PjnS7PmzT5

In [5]:
split_location = d.find(b"==") + 2

In [37]:
split_location

24

In [6]:
first = d[:split_location]
second = d[split_location:]

In [31]:
type(second)

bytes

In [58]:
second

b'eNqUvX3sZlV591uPVh0rgtqnIeQ3R89p4gs9kTZYE0wIreV3Izkx+oc5UB9lGJCX5041NqFacZwxHmTowzEx0UqNN6c1GjX8YWHagiiFQHGERJ7wEo1wkhEdcwI8ijl/mAyTBzj75bvW/uy913ff1/olxN3Vz3yv7772Wte97nWvvffv/A7+/mxn93dK/3f7v5P/308/tDe3HWuPxeX25r9jYPr//2Z3pJ31N7ujWElT/LMzzZ5/FnGLPlO8rn0ce+ZT/NC+Gfw7n1l/szuOVfA50uz57L8mn/p77EM3Z/6n7bH43N7925t3q/NJTfFPzzR7/mnEDefT+RQ/tG8G/zX5dD5Hmj3/NM6x+7v0mXHfSde6bWcfSDkUv+eSiTfxXftIc2c1ijX0pdUoVtbs+bMumWiKPwtxiz7TuXXtm1EfnvlkDsXvQdyiz6HPr8axCj6pKT77r8kn+6T4l10yudbiu/bafI40e/7MSyaa4s9E3HA+nU/2SfEvQ9xwPp1Paorv2pfqZOq7bftkbBTHdcPk9ub4GJhincz6m91RLDeus2bPP4u4ZZ8ab31NGI29mU/xqGOrY2DKPpP+ZncUq+RzpNnzz26rk9ZnoU6Kz+3dv715tzqftk5Ss+efRtxwPp1P8fhcWP0UTDifzudIs+efxjkW62S61u3/sg+4cZ28id+DcVqsk0NfWo1iuXGdNMWfhbhln+qTfU1Y8bxmPplD8XsQt+wz9/nVKFbJJzXFn7WtTlqfhTrJay3+Zah74Xy6OklN8Wcibjifzif7pPiXIW44n84nNcXn+l8zn9Tfd179q8zf3h6Lz+3Nf7eDCc8nqSn+4Zlmzz+MuOH5pPMpfmjfDP6r5pPG50iz57P/mnzq764P7c1zsfvaY/G5vfnvPjDhfFJT/GMzzZ5/DHHD+XQ+xQ/tm8F/TT6dz5Fmzz+GcwzPJ5lD8c9NvYl/Dkx4PjnS7PmzT5loiu/aa+eTzidzKP45MOH5pP

In [7]:
a1 = np.frombuffer(base64.decodebytes(first), dtype="<f4")
a2 = np.frombuffer(zlib.decompress(base64.decodebytes(second)), dtype="<f4")

In [8]:
print(len(a2))
print(a2.shape)

99264
(99264,)


In [9]:
print(a1)
print(a2.min(), a2.max(), a2.size, a2.size // 3)

[1.40130e-45 5.56394e-40 5.56394e-40 6.88598e-41]
0.0 80000.0 99264 33088


In [83]:
with open("/Users/swalkow2/Documents/yt/Datasets/Geoscience/solution-00100.0000.vtu") as data:
    xml = xmltodict.parse(data.read())

In [84]:
xml['VTKFile']['UnstructuredGrid']['Piece'][0]['PointData']['DataArray'][0]['@Name']
# coordinates = points data array
# cells data array = connectivity 
# for loop over xml to get array of conn, coords, offsets, types and a dict that maps field to vals

'velocity'

In [85]:
xml['VTKFile']['UnstructuredGrid']['Piece'][0]['PointData']

OrderedDict([('@Scalars', 'scalars'),
             ('DataArray',
              [OrderedDict([('@type', 'Float32'),
                            ('@Name', 'velocity'),
                            ('@NumberOfComponents', '3'),
                            ('@format', 'binary'),
                            ('#text',
                             'AQAAAAAPBgAADwYA1CwBAA==eNqUnWV0FFnXhSG4ayC4OyRVjQzduE2A4AMM7j4Q3C24E1yDBWdCuqrRSXALHjQEd9fgzreruuA9/a05s9aZX3c9K+zZ2XXvyenqW7eSX1odGQ//9U6foNyC4Yt/jZODr8201mWMJ4LPfDvD9ZMbP/P2/SFHcLkl5rhYrSMOgzeo0tp10+JJvtRx5QGnmlcnBf8aU82T4LcfBOvGmGrOejnLHM96c8xDcwr49YOl9eng/+UzTUyiLcZ4HPja+V9/8X/zafC0MY9dGT4cckwG3948yuULzvmkmgfACw3O4frp/998Us0x4OU/eblqWv4lef78+UwVZzo6pQsxxy3rzDJ57scpXRksPmmdr6syuDRPqnmt6zxzXP/1fA/NS+AHiyd25QSX5sn5NPipkGWulxVmOjqCf88w1pXT8i/Jk/NJNWPAi05L6joRN99B5+Rf9Sf+GtNrPQC8zfQZqjGmGa5UJpvjEUmiPbytAf8+b7jqAKeaY58N/zWmmjPAP9U7aP6/qObuLEHmeKPtgofmHvCGUbn11eCcTzonu4P32dPW5JxPmuHf4GEtHimpwDmfVHMEeIdSdUzO+aSaUeDl+5zVJoBL86Rzsuqz6ea489/LPK51efDVvZIoZ

In [86]:
type(xml['VTKFile']['UnstructuredGrid']['Piece'][0]['PointData']['DataArray'][0])

collections.OrderedDict

In [87]:
data = {}
for i in range(len(xml['VTKFile']['UnstructuredGrid']['Piece'][0]['PointData']['DataArray'])):
    # get names of arrays
    names = xml['VTKFile']['UnstructuredGrid']['Piece'][0]['PointData']['DataArray'][i]['@Name']
    types = xml['VTKFile']['UnstructuredGrid']['Piece'][0]['PointData']['DataArray'][i]['@type']
    print(names)
    # get binary code (as string)
    text = xml['VTKFile']['UnstructuredGrid']['Piece'][0]['PointData']['DataArray'][i]['#text']
    # re-encode string
    etext = text.encode()
    coord = np.frombuffer(base64.decodebytes(etext), dtype="<f4")
    print(coord)
    data[names] = [coord]

velocity
[1.40130e-45 5.56394e-40 5.56394e-40 1.07917e-40]
p
[1.40130e-45 1.85465e-40 1.85465e-40 2.58455e-41]
T
[1.40130e-45 1.85465e-40 1.85465e-40 1.08965e-41]
plastic_strain
[1.40130e-45 1.85465e-40 1.85465e-40 5.46759e-41]
crust_upper
[1.40130e-45 1.85465e-40 1.85465e-40 5.46913e-41]
crust_lower
[1.40130e-45 1.85465e-40 1.85465e-40 5.05911e-41]
density
[1.40130e-45 1.85465e-40 1.85465e-40 7.35962e-42]
current_cohesions
[1.40130e-45 1.85465e-40 1.85465e-40 2.18603e-43]
current_friction_angles
[1.40130e-45 1.85465e-40 1.85465e-40 2.17201e-43]
plastic_yielding
[1.40130e-45 1.85465e-40 1.85465e-40 2.10195e-43]
strain_rate
[1.40130e-45 1.85465e-40 1.85465e-40 9.44825e-41]
viscosity
[1.40130e-45 1.85465e-40 1.85465e-40 1.19096e-40]
heat_flux_map
[1.40130e-45 1.85465e-40 1.85465e-40 1.77124e-42]


In [88]:
print(data)

{'velocity': [array([1.40130e-45, 5.56394e-40, 5.56394e-40, 1.07917e-40], dtype=float32)], 'p': [array([1.40130e-45, 1.85465e-40, 1.85465e-40, 2.58455e-41], dtype=float32)], 'T': [array([1.40130e-45, 1.85465e-40, 1.85465e-40, 1.08965e-41], dtype=float32)], 'plastic_strain': [array([1.40130e-45, 1.85465e-40, 1.85465e-40, 5.46759e-41], dtype=float32)], 'crust_upper': [array([1.40130e-45, 1.85465e-40, 1.85465e-40, 5.46913e-41], dtype=float32)], 'crust_lower': [array([1.40130e-45, 1.85465e-40, 1.85465e-40, 5.05911e-41], dtype=float32)], 'density': [array([1.40130e-45, 1.85465e-40, 1.85465e-40, 7.35962e-42], dtype=float32)], 'current_cohesions': [array([1.40130e-45, 1.85465e-40, 1.85465e-40, 2.18603e-43], dtype=float32)], 'current_friction_angles': [array([1.40130e-45, 1.85465e-40, 1.85465e-40, 2.17201e-43], dtype=float32)], 'plastic_yielding': [array([1.40130e-45, 1.85465e-40, 1.85465e-40, 2.10195e-43], dtype=float32)], 'strain_rate': [array([1.40130e-45, 1.85465e-40, 1.85465e-40, 9.44825e

In [13]:
description = open("/Users/swalkow2/Documents/yt/Datasets/Geoscience/solution-00100.pvtu", "rb").readlines()

In [14]:
description

[b'<?xml version="1.0"?>\n',
 b'<!--\n',
 b'#This file was generated by the deal.II library on 2018/10/5 at 15:49:41\n',
 b'-->\n',
 b'<VTKFile type="PUnstructuredGrid" version="0.1" byte_order="LittleEndian">\n',
 b'  <PUnstructuredGrid GhostLevel="0">\n',
 b'    <PPointData Scalars="scalars">\n',
 b'    <PDataArray type="Float32" Name="velocity" NumberOfComponents="3" format="ascii"/>\n',
 b'    <PDataArray type="Float32" Name="p" format="ascii"/>\n',
 b'    <PDataArray type="Float32" Name="T" format="ascii"/>\n',
 b'    <PDataArray type="Float32" Name="plastic_strain" format="ascii"/>\n',
 b'    <PDataArray type="Float32" Name="crust_upper" format="ascii"/>\n',
 b'    <PDataArray type="Float32" Name="crust_lower" format="ascii"/>\n',
 b'    <PDataArray type="Float32" Name="density" format="ascii"/>\n',
 b'    <PDataArray type="Float32" Name="current_cohesions" format="ascii"/>\n',
 b'    <PDataArray type="Float32" Name="current_friction_angles" format="ascii"/>\n',
 b'    <PDataArra

In [1]:
yt.load_unstructured_mesh?
# connectivity = offset 
# node data (field names)


Object `yt.load_unstructured_mesh` not found.


In [1]:
# what meta data do I need
# What do I need to do to the arrays? 
# how do I load arrays and metadata into yt?